# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Image',
        ),
        migrations.AddField(
            model_name='image',
            name='article_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
